### ISSUE TITLE
Persistent storage and manifest.json

### ISSUE THREAD

**Issue by canDry** [davidahmed/my-lib#1]
A couple issues..
i) when I close down firefox (v76) the stored blacklist gets wiped.  My settings allow cookies and do not wipe them upon closing.  
ii) the manifest.json in your addon won't work with any of the recent versions.  It's missing:
```
    "applications": {
        "gecko": {
            "id": "xxx@yyy.com"
        }
    },
```

iii) lastly, the toolbar icon doesn't appear to do anything.  Should it open the blacklist panel?
  
Nice little tool for filtering out results.  Thanks!

**Comment by davidahmed** [comment]
On point iii)- No, currently the blacklist panel list is only accessible via View>Sidebar>Wiper
I'll try to reproduce (i),
 and thanks for the tip in (ii)- I'll fix it and update here.

**Comment by davidahmed** [comment]
Oops I think you have opened the issue in the wrong repo!

Here's the correct repo: https://github.com/davidahmed/wiper/issues

**Comment by davidahmed** [comment]
@canDry Please do open the issue in the correct repo. It's really helpful I think :) If not, then I'll recreate it myself at a later point in time.
